/**
 * Pixel Bat Animation — Canvas-based overlay
 * Detailed pixel-art bats (62x60, 8 animation frames) fly around the screen.
 * Based on Pixel Bat Animation by @coding.stella
 * Runs independently of the particle theme.
 */

const { sin, cos, hypot } = Math;

// Base64-encoded bat sprite data (2 bits per pixel, 4 pixels per byte)
// 0=transparent, 1=outline (configurable), 2=body (#202020), 3=eyes (#fff)
const BAT_DATA = {
    W: 62, H: 60,
    frames: [
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFUAAAAAAAAAAAAAAAFUAABaVAQAAAAAAAAAAAABVAAAWlQEAAAAAAAAAAAAVQAAAAapWUAAAAAAAAAAAakAAAABqqlAAAAAAAAAAAGpAAAAAaqpQAAAAAAAAABWlQAAAAFaqUAAAAAAAAABqpQAAAAAWqqQAAAAAAAAFqpAAAAAAVqqpAAAAAAAABaqQAAAAAFaqqQAAAAAAAAWqkAAAAAFqqqkAAAAAAAAaqpAAAAAAFqqqUQAAAAABWqqQQAAAABaqqlIAAAAAAVqqkEAAAAAWqqpSAAAAAAFqqqWQAAAAaqqqUAUAAAAAGqqqkAAAAWqqqlBaUAAAABqqqkAAAFaqqqlUWlAAAAAaqqpAAABWqqqpVFpQAAAAGqqlAAAAaqqqqaQFAAAAAWqqpRAAQBaqqqqkCAAAAAFqqqUQAEAWqqqqpAgAAAFQGqqQZQGAAaqqqlAAAAAWpBWqkGUWlBWqqqpQAAAAFqQFqpWqVqlWqqqpAFQAABakBaqVqlapVqqqqQBUAAABUqWqmqpqqlaqqqkAqAAAAAKQaqqqqqqqqqqkAaQAAAAAABqqqqqqqqqpUAAAAAAAAAAaqqqqqqqqqVAAAAAAAAAAFWqqqqqqqVQAAAAAAAABUIVqqqqqqpUAAAAAAAAABqoAauq/qqppVaQAAAAAAAaqAGrqv6qqaVWkAAAAAAACpSAa6r+qqqqqUAAAAAAAAAAAGqqqqqqqlQAAAAAAAAAAAAWqqqqqVUAAAAAAAAAAAAAFqqqqqlVAAAAAAAAAAAAAAFqqqlVAAAAAAAAAAAAAAAAFVVVAAAAAAAAAAAAAAAAABVVVQAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAUAAAAAAAAAAAAABAAAAAAFAAAAAAAAAAAAABlAAAAAGkBUAAAAAAAAAAFkAAAAAAWQaQAAAAAAAAABZAAAAAAFkGkAAAAAAAABRqQAAAAABaVqQAAAAAAAAVqQAAAAAABqlpQAAAAAAAaqkAAAAAAAapaUAAAAAAAGqpAAAAAAAGqWlAAAAAAABqlAAAAAAABqlpUAAAAAAFqpQAAAAAAFaqqpAAAAAABaqUAAAAAABZqqqQAqgAAAWqlAAAAAAAWaqqkAKoAAAVqpRUAAAAAFqqqqQCgAAAFaqplAAAAAAGqqqkACgAABWqqkAAAAAFBqqqpAAAAAAVqqpAAAAABQaqqqQAAAAAGqqqQAAAAAZaqqqkAAAAqhqqqQFAAVACqqqqlAAAAKoaqqkBQAFQAqqqqpQAAAAKGqqpAZQGUAFaqqqkAAAAABWqqRWVWqUAVqqqpCAAAAAFqpRqqaqpUFmqqpAoAAAABaqUaqmqqVBZqqqQKAAAAAWqlaqpqqqlWqqpUAAAAAAFqqmqqqqqpqqqqUAAAAAAAGqqqqqqqqqqqqQAAAAAAABqqqqqqqqqqqqkAAAAAAAAaqqqqqqqqqqqkAAAAAAAABWpqqqqqqqqpUAAAAAAAACpVauq/qqlqVVQAAAAAAAAqVWrqv6qpalVUAAAAAAAACgVa6r+qqpWpAAAAAAAAAAAAGqqqqqqVVAAAAAAAAAAAAAVaqqpVQAAAAAAAAAAAAAAFWqqqVUAAAAAAAAAAAAAAAAVVVUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAKAAAAAAAAKgAAAAAAAAAACgAAAAAAACoAAAAAAAAACgAAAAAAAAAqAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAogAAAKgAAAAAAAAAAAAAgKIAAACoAAAAgAAAAAAAAIACoAAAAAAACoAAAAAAAAAoAKAAAAAAACoAAAAAAAAAKgCoAAAAAAAqAAAAAAAAACoAqAAAAAKCigAAAAAAAAAqAKgAAAAAAqoAAAAAAAAAKKCoAAAAAAKqAAAAAAAAACigqAAAAAAKqgAAIAAAACgqqAgAAAAACqoAAAAoAIAqKqgKAKAAACKqAAAgKgACKoKqCgAAAAAiqgAAICoAAiqCqgoAAAAAIqoAIKAqAIACgqoKAAAAACqqCgCgKoKAAoKqCgAAAAAiqgoKoKqCgoKqqgoAAAAAIqoKCqCqgoKCqqoKAAAAACqqCqqgqqqqqqqqCAAAAAAqqiqqoKqqqqqqqgAAAAAAKqoqIKqqqqoqqqoAAAAAACqqKiCqqqqqKqqqAAAAAAAqqiAgqoKqqCqqqgAAAAAAKqqgAKqCKigqqqoAAAAAACqqoKCqAAIAKqqqAAAAAAAqqqCgqgACACqqqgAAAAAACqqAoCoAAgAqqqoAAAAAAAqqoAAgAAAoqiqoAAAAAAAKqqAAIAAAKKoqqAAAAAAAAqqgACAAAACqKqgAAAAAAAAqqgAAAAAAACqoAAAAAAAACqCAAAAAAAAqoAAAAAAAAAqggAAAAAAAKqAAAAAAAAAAqiAAAAAAAKqgAAAAAAAAACqgAAAAAACqoAAAAAAAAAAKgAAAAAAAggAAAAAAAAAACoAAAAAAAIIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAAAAAoAAAAAAAIAAFVQGUAAAAAAAAAAAAAAAAAGpVqQAAAAAAAAAAAAAAAABqVakAAAAAAAAAAAAFUAAFqqqqVAAAAAAAAAAACqAABaqqqpUAAAAAAAAAAAqgAAWqqqqVAAAAAAAAAAAapQAaqqqqqkAAAAAAAAAAGqpAGqqqqqpUAAEAAAAAABqqQBrqv6qqlAAGoAAAAAAaqkAa6r+qqpQABqAAAAAABqUAauq/qqqpAAakAAAAAAFQABqqqqmqqUABoAAAAAAAAAAaqqqpqqpUAAUAAAAAAAAAGqqqqaqqVAAFAAAAAAAAAAWqqqpqqpQAWlAAAAAAAAAamqqqaqqpUaqgAAACoBUAGqVVVWqqqlKqpQAAAqAVABqlVVVqqqpSqqUAAAKQKkBqqkFBaqqVAFqgAAAAACUAaqUAAWqqqlRaUAAAAAAAAGqlAAGqqqqpBQAAAAAAAABqpQABqqqqqQUAAAAAAUAFqqVAFqqqqlQAAAAAAAaQBaqqlRVqqqpQAAAAAAAGkAWqqpUVaqqqUAAAAAAACqUFqqqUAFaqqlQFAAAAABqqGqqqQAAWqqqkWlAAAAAaqhWqqkAAFqqqpaoAAAAAGqoVqqpAABaqqqWqAAAAAAalAGqqQAABqqpRqQAAAAABUABqqkAAAaqpBFQAAAAAAABQWqpAAAGqqVkAAAAAAAAAUFqqQAABqqlZAAAAAAAAAKBaqkAAAGqVqgAAAAAAAAVlBapAAABqlqkAAAAAAAAAEKBaQAAAaqqpAAAAAAAAABCgWkAAAGqqqQAAAAAAAAAAQBpAAABqalQAAAAAAAAAAAAFlAAAahUAAAAAAAAAAAAAAFQAAGkAAAAAAAAAAAAAAABUAABpAAAAAAAAAAAAAAAAAAAAVAAAAAAAAAAAAAAAAAAAAFQAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAUABWlAAAAAAAAAAAAAAAAFAAVpQAAAAAAAAAAAAAAABlAZaUAAAAAAAAAAAAAAAAalWpQAAAAAAAAAAAAAAABaqqqpUAAAAAAAAAAAAAAAWqqqqVAAAAAAAAAAAAAAAaqqqqqkAAAAAAAAAAAAAAaqqqqqqUAAAAAAAAAAAAAGqqqqqqlAAAAAAAAAAAAABqqqqqqqkAAAAAAAAAAAAAGuq/qqqpAAAAAAAAAAAVAGrqv6qqqkAAAAAAAAAAFQBq6r+qqqpAAAAAAAAAAWpAaqqqqqqqVQAAAAAAAAFqQBqqqqqqqalQCgAAAAAAFQAVqqqpqqqWpAoAAAAAABUAFaqqqaqqlqQKAAAAAAAAAFpaqqlqqqlQAAAAAAAAAABqpVZVaqqqUAAAAAAAAAAFapUBqlaqqlAAAAAAAAAABWqVAapWqqpQAAAAAAAAAAWqkABVFaqqpAZQAAAAAAAFqpAAABWqqqkKpQAAAoAqGqqVAABqqqqlBqUAAAKAKhqqlQAAaqqqpQalAAAAAAAaqqUAAGqqqqUBUAAAAAAAGqqqQAGqqqqpAgAAAAAAABqqqkABqqqqqQIAAAAAAAAaqqqAAFWqqqkAAAAAAAAAaqqlQAABqqqpAAAAAAABQBWqkAAAAGqqpAAAAAAAAUAVqpAAAABqqqQAAAAAAAaVBaqQAAAAaqqkqAAAAAAGoAWqkAAAAGqqUqQAAAAAABAFapAAAAAWqVBQAAAAAAAQBWqQAAAAFqlQUAAAAAAAAABqkAAAABapAgAAAAAAAABAGqUAAAAWlFQAAAAAAAAAoAVlAAAAFpaoAAAAAAAAAKAFZQAAABaWqAAAAAAAAABgABpAAABqVqQAAAAAAAAAAAAFQAAAaQFQAAAAAAAAAAAAAAAAAFQAAAAAAAAAAAAAAAAAAABUAAAAAAAAAAAAAAAAAAAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVAAAAAAAAAAAAAAAAAAAAFQAAAAAAAAAAAAAAAAAAAGpAAAAAAAAAAAAAAAAEABWqkAAAAAAAAAAAAAAABAAVqpAAAAAAAAAAAAAAABlAZaqQAAAAAAAAAAAAAAFZYGVVQAAAAAAAAAAAAAABapVqUAAAAAAAAAAAAAAAAWqValAAAAAAAAAAAAAAAAaqqqqlRQAAAAAAAAAAAAAGqqqqqpVAAAAAAAAAAAAABqqqqqqVQAAAAAAAAAAAABqqqqqqqkAAAAAAAAAAAAAauq/qqqpQAAAAAAAAAAAAFrqv6qqqVQAAAAAAAAAAABa6r+qqqlUAAAAAAAAAAAFaqqqqqqqlQAAAAAAAAAABWqqqqqqqqlUAAAAAAAAAJqaqqqqqmqqpAAAAAAAAACamqqqqqpqqqQAAAAAAAAAGqWqqqmqVqqpAAAAAAAAAGqqVaqpapaqqlCgAAAAAABqpQBVVpVWqqpQAAAAAAAAaqUAVVaVVqqqUAAAAAAAAGqlQAABqlaqqqQAAAAAAAWqqkAAABVqqqqkAAAAAAAFqqqQAAAAaqqqpAAAAAAABaqqkAAAAGqqqqQAAAAAAAWqqpAAAABqqqqkAAAAAKAFqqqQAAABqqqqpKoAAACgBaqqkAAAAaqqqqSqAAAAAAVqpaUAABaWqqpQqgAAAAAAaqVVAAABQaqqUAAAAAAAAGqlAAAAAAGqqlCgAAAAAABqpQAAAAABqqpQoAAAAAAAWqUAAAAAAWqmUAAAAAAAABqlAAAAAABqpQAAAAAAACoFqkAAAAAAalAAAAAAAAAqBapAAAAAAGpQAAAAAAAAKgBqQAAAAABqUAAAAAAAAAAAFZAAAAABqQAAAAAAAAAAAABQAAAAFpQAAAAAAAAAAAAAUAAAABaUAAAAAAAAAAAAAAAAAAABQqAAAAAAAAAAAAAAgAAAAAIAAAAAAAAAAAAAAIAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoAAAABAAAAAAAAAAAAAAAqAAAAAQAAAAAAAAAAAAAAqoAAABaUKgAAAAAAAAAACqCAAIAqlCqgAAAAAAAAACqKAAIAaUACqAAAAAAAAAAqigACAGlAAqgAAAAAAAAAqqAAAAAAAACqAAAAAAAAAKqAAIAAAAKoqgAAAAAAAAqqgACAAACCqKqgAAAAAAAKqoAAgAAAgqiqoAAAAAAAIKoKgKgAKACqqqAAAAAAACqqioqoACgAqqqgAAAAAAAqqoqKqAAoAKqqoAAAAAAAIKqACqooqICqqggAAAAAAqqggIqqKqqAqqoIAAAAAAKqoKCKqqqqqKqqCAAAAAACqqCgiqqqqqiqqggAAAAAAqqgqqqCqqqqqqqoAAAAAAKqoCqqgqqqqqqqCAAAAAACiqAgKoKqKioqqqigAAAAAoqgICqCqioqKqqooAAAAAKqoCAKgKoqACoKqKAAAAACiqAAioCoAgAqCqigAAAAAoqgAACAqAAoqgqooAAAAAKKoAAAgKgAKKoKqKAAAAAAKqAAAACAAgCoqqCgAAAAACqgAACAAAAAgKqgoAAAAAAKoAAAAAAAAACiAqAAAAAACqAAAAAAAAAAogKgAAAAAAogAAAAAAAAAKgCAAAAAAAAoAAAAAAAAACoAgAAAAAAAKAAAAAAAAAAqAIAAAAAAAAqAAAAAAAAAKAAAoAAAAAACgAAAAAAAAIACAAAAAAAAAAAAAAAAAACAgAAAAAAAAAAAAAAAAAAAgIAAAAAAAAACoAAAAAAAAAAAAAAAAAAAACAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "AAAAAAAAAAVUAAAAAAAAAAAAAAAAAAAFVAAAAAAAAAAAAAAAAFUABalQAAAAAAAAAAAAABWpAAGqpQAAAAAAAAAAAAAVqQABqqUAAAAAAAAAAAAAapQAAFqqUAAAAAAAAAAAAapAAABaqqQAAAAAAAAAAAGqQAAAWqqkAAAAAAAAAAAWqkAAAAaqqUAAAAAAAAABaqkAAAAGqqqQAAAAAAAAAaqpAAAAAaqqkAAAAAAAAAGqqQAAAAGqqpAAAAAAAAABqqkAAKABqqqkAAAAAAAAVqqpAAAAAaqqpAAAAAAAAGqqqQAAAAaqqpVQAAAAAABqqqkAAAAGqqqVUAAAAAAQFqqqQAAAWqqqmqQAAAAAoBaqqlQAAaqqqpapQAAAAGAWqpUAAAaqqqqpaUAAAABgFqqVAAAGqqqqqWlAAAAAEAGqlAAABaqqqqVqgAAAAAAVqpRUBQBaqqVRaoAAAAAAFaqUVAUAWqqlUWqAAAAAAFaqqZQGUFqqqUApQAAAAFABqpWpWqVaqqlQFAAAAAWqQGpqqaqpqqqkAAAAAAAFqkBqaqmqqaqqpAAAAAAAWqpAaqqqqqqqqVAAIAAAAFqqgFaqqqqqqqUAAAVAAAAFpUAVqqqqqqpUAAAalAAABaVAFaqqqqqqVAAAGpQAAABVAAGqqqqqqqRVUBqUAAAAAFUBq6r+qqqlqUAFQAAAAAWqQGuq/qqqqqQAAAAAAAAFqkBrqv6qqqqkAAAAAAAACqpAaqqqqqqpUAAAAAAAAAWpABaqqqqqVAAAAAAAAAAAVAABaqqpVQgAAAAAAAAAAFQAAWqqqVUIAAAAAAAAAAAAAAAVVVUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAKgAAAAAAAAAAAAAAAAAAACoAAAAAAAAACoAAAAAAAAApAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    ]
};

const SPRITE_W = BAT_DATA.W;
const SPRITE_H = BAT_DATA.H;

/**
 * Decode a base64 frame into a 2D pixel grid
 */
function decodeFrame(b64) {
    const bytes = Uint8Array.from(atob(b64), c => c.charCodeAt(0));
    const paddedW = Math.ceil(SPRITE_W / 4) * 4;
    const grid = [];

    for (let y = 0; y < SPRITE_H; y++) {
        const row = [];
        for (let col = 0; col < paddedW; col += 4) {
            const byteIdx = y * (paddedW / 4) + (col / 4);
            const b = bytes[byteIdx] || 0;
            row.push((b >> 6) & 3);
            row.push((b >> 4) & 3);
            row.push((b >> 2) & 3);
            row.push(b & 3);
        }
        grid.push(row.slice(0, SPRITE_W));
    }
    return grid;
}

/**
 * Pre-render a bat frame to an offscreen canvas
 */
function renderFrame(grid, colors, pixelSize) {
    const canvas = document.createElement('canvas');
    canvas.width = SPRITE_W * pixelSize;
    canvas.height = SPRITE_H * pixelSize;
    const ctx = canvas.getContext('2d');

    for (let y = 0; y < SPRITE_H; y++) {
        const row = grid[y];
        for (let x = 0; x < SPRITE_W; x++) {
            const type = row[x];
            if (type === 0) continue;
            ctx.fillStyle = colors[type];
            ctx.fillRect(x * pixelSize, y * pixelSize, pixelSize, pixelSize);
        }
    }
    return canvas;
}

/**
 * Initialize pixel bat overlay on a container element.
 * @param {HTMLElement} container
 * @param {object} config - { color, bodyColor, eyeColor, batCount, scale, flapSpeed }
 * @returns {function} cleanup function
 */
export function initPixelBat(container, config) {
    const outlineColor = config.color || '#54556b';
    const bodyColor = config.bodyColor || '#202020';
    const eyeColor = config.eyeColor || '#ffffff';
    const batCount = config.batCount || 5;
    const pixelSize = config.scale || 2;
    const flapSpeed = config.flapSpeed || 120;

    const colors = {
        1: outlineColor,
        2: bodyColor,
        3: eyeColor,
    };

    // Decode and pre-render all frames
    const decodedFrames = BAT_DATA.frames.map(b64 => decodeFrame(b64));
    const frameCanvases = decodedFrames.map(grid => renderFrame(grid, colors, pixelSize));

    // Create overlay canvas
    const canvas = document.createElement('canvas');
    canvas.style.cssText = 'position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:2;';
    container.appendChild(canvas);

    const ctx = canvas.getContext('2d');
    let w, h;

    const bats = Array.from({ length: batCount }, () => {
        return {
            x: Math.random() * innerWidth,
            y: Math.random() * innerHeight,
            targetX: Math.random() * innerWidth,
            targetY: Math.random() * innerHeight,
            speed: 0.3 + Math.random() * 0.7,
            frame: Math.floor(Math.random() * frameCanvases.length),
            frameTimer: 0,
            dir: 1,
            seed: Math.random() * 100,
        };
    });

    const FRAME_DURATION = flapSpeed;
    let animId;
    let lastTime = 0;

    function animate(time) {
        const dt = lastTime ? time - lastTime : 16;
        lastTime = time;

        if (w !== innerWidth || h !== innerHeight) {
            w = canvas.width = innerWidth;
            h = canvas.height = innerHeight;
        }

        ctx.clearRect(0, 0, w, h);

        bats.forEach(bat => {
            bat.x += (bat.targetX - bat.x) * 0.003 * bat.speed;
            bat.y += (bat.targetY - bat.y) * 0.003 * bat.speed;
            bat.y += sin(time * 0.002 + bat.seed) * 0.4;
            bat.x += cos(time * 0.0015 + bat.seed * 2) * 0.2;

            if (hypot(bat.targetX - bat.x, bat.targetY - bat.y) < 80) {
                bat.targetX = Math.random() * w;
                bat.targetY = Math.random() * h;
            }

            const margin = 60;
            if (bat.x < -margin) bat.x = w;
            if (bat.x > w + margin) bat.x = 0;
            if (bat.y < -margin) bat.y = h;
            if (bat.y > h + margin) bat.y = 0;

            bat.dir = bat.targetX > bat.x ? -1 : 1;

            bat.frameTimer += dt;
            if (bat.frameTimer > FRAME_DURATION) {
                bat.frameTimer = 0;
                bat.frame = (bat.frame + 1) % frameCanvases.length;
            }

            const sprite = frameCanvases[bat.frame];
            ctx.save();
            ctx.translate(bat.x, bat.y);
            ctx.scale(bat.dir, 1);
            ctx.drawImage(sprite, -sprite.width / 2, -sprite.height / 2);
            ctx.restore();
        });

        animId = requestAnimationFrame(animate);
    }

    animId = requestAnimationFrame(animate);

    return () => {
        cancelAnimationFrame(animId);
        canvas.remove();
    };
}
